public class ManejoExcepciones {
    public static void main(String[] args) {
        try {
            int resultado = 10 / 0;  
        } catch (ArithmeticException e) {
            System.out.println("Error: Divisi√≥n por cero.");
        } finally {
            System.out.println("Este bloque se ejecuta siempre.");
        }
    }
}